### ISSUE TITLE
microsoft support

### ISSUE THREAD

**Issue by oodvg** [EvernoteMC/hypixel-guild-chat-py#1]
adding microsoft support since Mojang is migrating.

**Comment by AddmanMinecraft** [comment]
I will be adding something like this in a new one in a few weeks.

**Comment by MGValues** [comment]
Any update on the progress? This has worked very well for me, but I'd appreciate being able to create an account and use it instead of having to use an alt that existed before migration.

**Comment by EvernoteMC** [comment]
Sorry for the lack of updates on this project. Unfortunately the library I use for this project hasn't been updated in a while, so the only choice I have is to rewrite this to work with a different library. I'm currently working on one using Mineflayer, which should be available quite soon. I'll make sure to update you once it's available to try out.

**Comment by oodvg** [comment]
> Sorry for the lack of updates on this project. Unfortunately the library I use for this project hasn't been updated in a while, so the only choice I have is to rewrite this to work with a different library. I'm currently working on one using Mineflayer, which should be available quite soon. I'll make sure to update you once it's available to try out.

you can use Nextcord (a fork of Discord.py)
